Schedule/Schedule/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('add_favorite/<int:pk>', user_views.add_favorite, name='add_favorite'),
    path('', include('main.urls')),
    path('search/', include('haystack.urls')),
]

Schedule/main/urls.py
from django.urls import path
from .views import cian_render, delete_apartment, load_apartment

app_name = 'main'

urlpatterns = [
    path('', cian_render, name='cian_render'),
    path('delete', delete_apartment, name='delete_apartment'),
    path('load', load_apartment, name='load_apartment'),
]

Schedule/main/models.py
from __future__ import unicode_literals
import os

from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin,
)


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves a new user."""
        if not email:
            raise ValueError("Users must have an email address.")
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, password=None, **extra_fields):
        """Creates and saves a superuser."""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model with email instead of username."""

    favorites = models.ManyToManyField('Apartment', null=True, blank=True)
    email = models.EmailField(max_length=120, unique=True)
    name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'


class Apartment(models.Model):
    address = models.CharField(db_index=True, max_length=512)
    total_area = models.PositiveSmallIntegerField()
    floor = models.CharField(max_length=7)
    price = models.PositiveIntegerField()

    def __str__(self):
        return f'{self.address}, {self.total_area} м², {self.floor}, {self.price} руб/мес'

Schedule/main/views.py
import json

from django.shortcuts import render, redirect
from django.contrib.postgres.search import SearchVector
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import get_user_model

from .models import Apartment
from .tasks import main

def cian_render(request, queryset=None):
    query = request.GET.get('query')
    if query:
        search_vector = SearchVector('address', 'total_area', 'floor', 'price')
        queryset = Apartment.objects.annotate(search=search_vector) \
                                    .filter(search=request.GET.get('query'))
    else:
        queryset = queryset or Apartment.objects.all()

    paginator = Paginator(queryset, 20)
    page = request.GET.get('page')
    
    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 5 if index >= 5 else 0
    end_index = index + 5 if index <= index - 5 else max_index
    page_range = paginator.page_range[start_index:end_index]

    User = get_user_model()
    last = User.objects.last()
    
    context = {
        'items': items,
        'page_range': page_range,
        'ads_count': queryset.count(),
        'query': query,
        'max_index': max_index,
        'last': last,
        'favs': request.user.favorites.all() if request.user.is_authenticated else {},
    }
    return render(request, 'cian_table.html', context)


def delete_apartment(request):
    Apartment.objects.all().delete()
    return redirect('main:cian_render')


def load_apartment(request):
    Apartment.objects.all().delete()
    main.delay()
    return redirect('main:cian_render')

Schedule/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.forms import CharField, ModelForm, PasswordInput, TextInput
from django.shortcuts import redirect, render


class CreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = 'email', 'name'


def register(request):
    if request.method == "POST":
        form = CreationForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data.get('name')
            messages.success(request, f'Your account created, {name}! Now you can log in.')
            form.save()
            return redirect('main:cian_render')
    else:
        form = CreationForm()
    
    return render(request, 'users/register.html', {'form': form})

def profile(request):
    user = request.user
    return render(request, 'users/profile.html',
                  {'favs': user.favorites.all()})

@login_required(login_url='login')
def add_favorite(request, pk):
    user = request.user
    fav = user.favorites.filter(pk=pk)
    if fav:
        user.favorites.remove(pk)
    else: 
        user.favorites.add(pk)
    # print(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))

Schedule/main/templates/autocomplete.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Autocomplete Example</title>
</head>
<body>
  <h1>Autocomplete Example</h1>

  <form method="post" action="/search/" class="autocomplete-me">
    <input type="text" id="id_q" name="q">
    <input type="submit" value="Search!">
  </form>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script type="text/javascript">
    // In a perfect world, this would be its own library file that got included
    // on the page and only the ``$(document).ready(...)`` below would be present.
    // But this is an example.
    var Autocomplete = function(options) {
      this.form_selector = options.form_selector
      this.url = options.url || 'http://127.0.0.1:8000/'
      this.delay = parseInt(options.delay || 300)
      this.minimum_length = parseInt(options.minimum_length || 3)
      this.form_elem = null
      this.query_box = null
    }

    Autocomplete.prototype.setup = function() {
      var self = this

      this.form_elem = $(this.form_selector)
      this.query_box = this.form_elem.find('input[name=q]')

      // Watch the input box.
      this.query_box.on('keyup', function() {
        var query = self.query_box.val()

        if(query.length < self.minimum_length) {
          return false
        }

        self.fetch(query)
      })

      // On selecting a result, populate the search field.
      this.form_elem.on('click', '.ac-result', function(ev) {
        self.query_box.val($(this).text())
        $('.ac-results').remove()
        return false
      })
    }

    Autocomplete.prototype.fetch = function(query) {
      var self = this

      $.ajax({
        url: this.url
      , data: {
          'q': query
        }
      , success: function(data) {
          self.show_results(data)
        }
      })
    }

    Autocomplete.prototype.show_results = function(data) {
      // Remove any existing results.
      $('.ac-results').remove()

      var results = data.results || []
      var results_wrapper = $('<div class="ac-results"></div>')
      var base_elem = $('<div class="result-wrapper"><a href="#" class="ac-result"></a></div>')

      if(results.length > 0) {
        for(var res_offset in results) {
          var elem = base_elem.clone()
          // Don't use .html(...) here, as you open yourself to XSS.
          // Really, you should use some form of templating.
          elem.find('.ac-result').text(results[res_offset])
          results_wrapper.append(elem)
        }
      }
      else {
        var elem = base_elem.clone()
        elem.text("No results found.")
        results_wrapper.append(elem)
      }

      this.query_box.after(results_wrapper)
    }

    $(document).ready(function() {
      window.autocomplete = new Autocomplete({
        form_selector: '.autocomplete-me'
      })
      window.autocomplete.setup()
    })
  </script>
</body>
</html>

Schedule/main/templates/cian_table.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
</head>

<body>
  <h1 class="px-4 mb-0 display-4 bg-light text-dark">День добрый!
    Квартирку выбираем?</h1>
  <div class="row bg-light">
    <div class="col-5">
      <form method="GET" class="input-group m-3 mt-4 ml-4" action="{% url 'main:cian_render' %}">
        <input class="form-control" placeholder="Я ищу..." name="query" value="{{ request.GET.query }}">
        <div class="input-group-append">
          <button class="btn btn-dark" type="submit">Найти</button>
        </div>
      </form>
      
      <div class="container ml-2">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
          {% endfor %}
        {% endif %}
      </div>
    </div>

    <div class="col-7">
      {% if user.is_authenticated %}
      <a href="{% url 'logout' %}" class="h5 float-right my-4 mx-4 text-secondary bg-light">Выйти</a>
      <a href="{% url 'profile' %}" class="h5 float-right my-4 text-success bg-light">Избранное</a>
      {% else %}
      <a href="{% url 'register' %}" class="h5 float-right my-4 mx-4 text-dark">Регистрация</a>
      <a href="{% url 'login' %}" class="h5 float-right my-4 text-success bg-light">Войти</a>
      {% endif %}
    </div>
  </div>

  <table class="table table-sm table-hover table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Площадь</th>
        <th>Этаж</th>
        <th>Цена, руб/мес</th>
        <th>Адрес
          <a href="{% url 'main:delete_apartment' %}"
            class="float-right text-danger mr-3">Удалить всё</a>
          <a href="{% url 'main:load_apartment' %}"
            class="float-right text-info mx-3">Обновить выдачу</a>
          <a class="float-right text-dark">Всего объявлений: {{ ads_count }}</a>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for item in items %}
      <tr>
        <th scope="row">{{ item.id }}</th>
        <td>{{ item.total_area }} м²</td>
        <td>{{ item.floor }}</td>
        <td>{{ item.price }}</td>
        {% if user.is_authenticated and item in favs %}
        <td>{{ item.address }}<a class="ml-2" title="Убрать из избранного" href="{% url 'add_favorite' pk=item.pk %}">★</a> </td>
        {% else %}
        <td>{{ item.address }}<a class="ml-2" title="В избранное" href="{% url 'add_favorite' pk=item.pk %}">☆</a> </td>
        {% endif %}  
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include 'pagination.html' %}
</body>

</html>

Schedule/main/templates/pagination.html
{% if items.has_other_pages %}
  <div class="col-4 text-center offset-4 pagination-set">
    <nav aria-label="">
      <ul class="pagination">
        {% if items.has_previous %}
          <li class="page-item">
            <a href="?page={{ items.previous_page_number }}{% if query %}&query={{ query }}{% endif %}" class="page-link text-dark">⟵</a>
          </li>
        {% else %} 
          <li class="page-item disabled">
            <a class="page-link text-dark">
              <span>⟵</span>
            </a> 
          </li> 
        {% endif %}

        {% if items.number > 4 %}
          <li class="page-item text-dark">
            <a href="?page={{ 1 }}{% if query %}&query={{ query }}{% endif %}"
            class="page-link text-dark">1</a>
          </li>
        {% endif %}

        {% if items.number > 5 %}
          <li class="page-item page-link text-dark disabled">
            <a>…</a>
          </li>
        {% endif %}
          
        {% for i in page_range %}
          {% if items.number == i %} 
            <li class="page-item active">
              <a class="page-link bg-dark border-dark">{{ i }}<span class="sr-only">(current)</span></a>
            </li>
          {% elif items.number|add:"-4" < i and i < items.number|add:"4" %}
            <li class="page-item">
              <a href="?page={{ i }}{% if query %}&query={{ query }}{% endif %}"
              class="page-link text-dark">{{ i }}</a>
            </li>
          {% endif %}
        {% endfor %}

        {% if items.number < max_index|add:"-4" %}
          <li class="page-item page-link text-dark disabled">
            <a>…</a>
          </li>
        {% endif %}

        {% if items.number < max_index|add:"-4" %}
          <li class="page-item text-dark">
            <a href="?page={{ max_index }}{% if query %}&query={{ query }}{% endif %}"
            class="page-link text-dark">{{ max_index }}</a>
          </li>
        {% endif %}

        {% if items.has_next %}
          <li class="page-item">
            <a href="?page={{ items.next_page_number }}{% if query %}&query={{ query }}{% endif %}"
            aria-label="Next" class="page-link text-dark">⟶</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link text-dark"><span>⟶</span></a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endif %}

Schedule/users/templates/users/login.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Log in</title>
	<link rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
		crossorigin="anonymous">
</head>

<body>
	<div class="container">
		<div class="row justify-content-center">
			<div class="content-section m-5 col-6">
				<form method="POST">
          <fieldset class="form-group">
            <legend class="border-bottom mb-4">Войдите!</legend>
            {% csrf_token %}
						{{ form|crispy }}
					</fieldset>
					<div class="form-group">
						<button class="btn btn-outline-info" type="submit">Log in</button>
					</div>
				</form>
				<div class="border-top pt-3">
					<small class="text-muted">
						Нет аккаунта? Не беда!<a href="{% url 'register' %}" class="ml-2">Создать</a>
					</small>
				</div>
			</div>
		</div>
	</div>
</body>

</html>

Schedule/users/templates/users/logout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Log out</title>
  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
</head>

<body>
  <div class="container mt-4">
    <div class="display-4 mb-4">You've been logged out.</div>
    <div class="border-top pt-3">
      <a href="{% url 'login' %}" class="ml-2">Log in again</a>
    </div>
  </div>
</body>

</html>

Schedule/users/templates/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet"
  href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
  crossorigin="anonymous">
  <title>{{ user }}'s profile</title>
</head>
<body>
  <h1 class="px-4 mb-0 display-4 bg-light text-dark pb-3">Избранное</h1>
  <table class="table table-sm table-hover table-striped">
      <thead>
        <tr>
          <th>#</th>
          <th>Площадь</th>
          <th>Этаж</th>
          <th>Цена, руб/мес</th>
          <th>Адрес
            <a class="float-right text-dark mr-3">Всего избранных: {{ favs.count }}</a>
            <a class="float-right text-success mr-3" href="{% url 'main:cian_render' %}">На главную</a> 
          </th>
        </tr>
      </thead>
      <tbody>
        {% for fav in favs %}
        <tr>
          <th scope="row">{{ fav.id }}</th>
          <td>{{ fav.total_area }} м²</td>
          <td>{{ fav.floor }}</td>
          <td>{{ fav.price }}</td>
          <td>{{ fav.address }}<a class="ml-2" href="{% url 'add_favorite' pk=fav.pk %}" title="Удалить">🗑</a> </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
</body>
</html>

Schedule/users/templates/users/register.html
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Registration</title>
	<link rel="stylesheet"
		href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
		integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
		crossorigin="anonymous">
</head>

<body>
	<div class="container">
		<div class="row justify-content-center">
			<div class="content-section m-5 col-6">
				<form method="POST">
					{% csrf_token %}
					<fieldset class="form-group">
						<legend class="border-bottom mb-4">Join Today</legend>
						{{ form|crispy }}
					</fieldset>
					<div class="form-group">
						<button class="btn btn-outline-info" type="submit">Sign Up</button>
					</div>
				</form>
				<div class="border-top pt-3">
					<small class="text-muted">
						Already have an account? <a href="#" class="ml-2">Sign In</a>
					</small>
				</div>
			</div>
		</div>
	</div>
</body>

</html>